name = "bim-carbon-platform"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-16"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "bim"
database_id = "fa8e1fb6-bb77-4a77-ba6c-50e64670da54"
